const DELAY = 1000 / 60
const MAX_WIDTH = window.innerWidth
const MAX_HEIGHT = window.innerHeight

var DRAW = true

const MAX_SPEED = 10
const BASE_SPEED = 6

// const DISTANCE_BETWEEN_PIPE = MAX_WIDTH / 4
const BIRD_HEIGHT = 30
const BRAIN_BLOCK_SIZE = 10
const OBJECT_WIDTH = 60

const POPULATION = 1000
const ERAS = 1000

const BASE_X_POSITION_INFO = 150
const BASE_Y_POSITION_INFO = 100
const BASE_X_POSITION_BRAIN = MAX_WIDTH / 2
const BASE_Y_POSITION = MAX_HEIGHT / 2
const BASE_X_POSITION = 150
const LIMIT_X_POSITION = MAX_WIDTH - (MAX_WIDTH / 3)

const MIN_HEIGHT_PIPE = BASE_Y_POSITION * 10 / 100
const DISTANCE_BETWEEN_PIPE = MIN_HEIGHT_PIPE * 4
const HEIGHT_ALLOWED = BASE_Y_POSITION * 40 / 100
const DISTANCE_TO_NEXT_PIPE = MAX_WIDTH * 40 / 100